name: Conda Package Build

on:
  release:
    types: [published]

jobs:
  conda-build:
    name: Build Conda Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: build-env

      - name: Install build tools
        run: |
          conda install -y conda-build pip
          pip install grayskull

      - name: Generate Conda recipe with Grayskull
        run: |
          grayskull pypi package_publishing_example

      - name: Build Conda package
        run: |
          conda build package_publishing_example/

      - name: Show output location
        run: conda build package_publishing_example/ --output
