name: Deploy Docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Copy assignment
        run: |
          mkdir -p docs
          cp assignment.md docs/index.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: docs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
