name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload static content
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2