name: Deploy Docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Pages
        uses: actions/configure-pages@v3
        
      - name: Copy assignment
        run: cp -r assignment.md docs/index.md

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

      # 👇 Workaround for GH bug: force fetch of upload-artifact@v3
      - name: Workaround: Include upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: README.md

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
